FROM ubuntu:22.04
RUN apt-get update && \
  DEBIAN_FRONTEND=noninteractive apt-get install -y \
  lsb-release git curl wget vim locales build-essential rerun reflex \
  build-essential libssl-dev zlib1g-dev \
  libbz2-dev libreadline-dev libsqlite3-dev llvm libncurses5-dev \
  libncursesw5-dev tk-dev libffi-dev liblzma-dev \
  libpq-dev tzdata
RUN localedef -i en_US -f UTF-8 en_US.UTF-8
ENV LANG en_US.UTF-8
ENV LANGUAGE en_US.UTF-8
ENV LC_ALL en_US.UTF-8

ENV RBENV_HASH "311217208122e4c7e49c2bff9069912e2a07e873"
ENV RUBY_BUILD_HASH "895f8fa40f117afdc6b441de3557ba58193803e9"
ENV NODENV_HASH "15375bb6d6b5215a47c56cdd8bf347d4f360bf34"
ENV NODE_BUILD_HASH "0b1e2d31d96b4b5cbc385494b24c03382a714ea2"
ENV GOENV_HASH "6015352fb604850af7dd5726b9201b93276d7adc"
ENV PYENV_HASH "e82e12739c5fdaa0ccd554d648a092dc12402a5f"

ENV PATH="/root/.rbenv/bin:/root/.rbenv/shims:$PATH"
RUN git clone https://github.com/rbenv/rbenv.git /root/.rbenv && \
  cd /root/.rbenv && git checkout $RBENV_HASH && cd /root && \
  git clone https://github.com/rbenv/ruby-build.git /root/.rbenv/plugins/ruby-build && \
  cd /root/.rbenv/plugins/ruby-build && git checkout $RUBY_BUILD_HASH
ENV RUBY_CONFIGURE_OPTS=--disable-install-doc
ENV BUNDLE_PATH=.gems

ENV PATH="/root/.nodenv/bin:/root/.nodenv/shims:$PATH"
RUN git clone https://github.com/nodenv/nodenv.git /root/.nodenv && \
  cd /root/.nodenv && git checkout $NODENV_HASH && cd /root && \
  git clone https://github.com/nodenv/node-build.git /root/.nodenv/plugins/node-build && \
  cd /root/.nodenv/plugins/node-build && git checkout $NODE_BUILD_HASH

ENV PATH="/root/.goenv/bin:/root/.goenv/shims:$PATH"
RUN git clone https://github.com/syndbg/goenv /root/.goenv && \
  cd /root/.goenv && git checkout $GOENV_HASH

ENV PATH="/root/.pyenv/bin:/root/.pyenv/shims:$PATH"
RUN git clone https://github.com/pyenv/pyenv /root/.pyenv && \
  cd /root/.pyenv && git checkout $PYENV_HASH
