FROM alpine:3.10 as compiler
RUN apk add --update build-base ocaml bash wget
ENV UNISON_VERSION 2.51.2
ENV UNISON_MD5 11991eddcf6fdd8b50041eefe44bad61
RUN wget https://github.com/bcpierce00/unison/archive/v${UNISON_VERSION}.tar.gz
RUN echo "${UNISON_MD5}  /v${UNISON_VERSION}.tar.gz" > /tmp/md5s && md5sum -s -c /tmp/md5s
RUN tar xvf v${UNISON_VERSION}.tar.gz && \
  cd unison-$UNISON_VERSION && \
  sed -i -e 's/GLIBC_SUPPORT_INOTIFY 0/GLIBC_SUPPORT_INOTIFY 1/' src/fsmonitor/linux/inotify_stubs.c && \
  make && \
  cp src/unison* /usr/local/bin/ && \
  cd .. && \
  rm -fr /unison-${UNISON_VERSION} /v${UNISON_VERSION}.tar.gz
FROM alpine:3.10
RUN apk add --update bash
COPY --from=compiler /usr/local/bin/unison* /usr/local/bin/
